name: Regenerate static pages

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 00 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build site
        uses: actions/setup-node@v3
        with:
          node-version: '14.21.3'
      - name: Installing dependencies
        run: npm install
      - name: Building
        run: npm run build
      - name: Update repository
        uses: stefanzweifel/git-auto-commit-action@v5
