name: Build site

on:
  repository_dispatch:
  schedule:
    - cron: '0 00 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build site
        uses: actions/setup-node@v3
        with:
          node-version: '14.21.3'
      - run: npm run build
